name: Pipeline Runner
description: Pipeline runner.
runs:
  using: node12
  main: index.js
branding:
  icon: chevron-up
  color: blue
inputs:
  tag-prefix:
    description: 'Prefix that is used for the git tag'
    default: 'v'
  patch-wording:
    description: 'Words list that trigger a patch version bump 0.0.1'
    default: 'fix'
    required: false
  minor-wording:
    description: 'Words list that trigger a minor version bump 0.1.0'
    default: 'feat'
    required: false
  major-wording:
    description: 'Words list that trigger a major version bump 1.0.0'
    default: 'chng'
    required: false
  skip-tag:
    description: 'Avoid to add a TAG to the version update commit'
    default: 'false'
    required: false
  skip-commit:
    description: 'Avoid to add a commit after the version is bumped'
    default: 'false'
    required: false
  skip-push:
    description: 'If true, skip pushing any commits or tags created after the version bump'
    default: false
    required: false
  PACKAGEJSON_DIR:
    description: 'Custom dir to the package'
    default: ''
    required: false
  commit-message:
    description: 'Set a custom commit message for version bump commit'
    default: ''
    required: false
outputs:
  newTag:
    description: 'The newly created tag'
